name: apply

on:
  push:
    branches:
      - main

jobs:
  list:
    uses: ./.github/workflows/workflow_call_list.yaml
    permissions:
      contents: read
      pull-requests: read

  apply:
    name: apply (${{ matrix.target.target }})
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    needs:
      - list
    permissions:
      contents: read
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{ matrix.target.working_directory }}
      TFACTION_JOB_TYPE: ${{ matrix.target.job_type }}
    if: join(fromJSON(needs.list.outputs.targets), '') != ''
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.list.outputs.targets) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create GitHub App installation access token
        id: token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-actions: read
          permission-contents: write
          permission-pull-requests: write

      - name: Set up tfaction
        uses: suzuki-shunsuke/tfaction@v2.0.3
        with:
          action: setup
          github_token: ${{ steps.token.outputs.token }}

      - name: Terraform init
        uses: suzuki-shunsuke/tfaction@v2.0.3
        with:
          action: terraform-init
          github_token: ${{ steps.token.outputs.token }}

      - name: Terraform apply
        uses: suzuki-shunsuke/tfaction@v2.0.3
        with:
          action: apply
          github_token: ${{ steps.token.outputs.token }}
